graph TB
  subgraph legend["Legend"];
    legend_gateway["Gateway"];
    legend_switch["Switch"];
    legend_ap["AP"];
    legend_client["Client"];
    legend_other["Other"];
    legend_poe_a["PoE Link A"];
    legend_poe_b["PoE Link B"];
    legend_no_poe_a["Link A"];
    legend_no_poe_b["Link B"];
    legend_poe_a ---|⚡| legend_poe_b;
    legend_no_poe_a --- legend_no_poe_b;
  end
